
## Snakemake configuration
## @Author Floris Barthel

#### GLOBAL PARAMETERS

## Full path to GDC keyfile
gdc_token: "/home/barthf/gdc-user-token.2018-05-23T11_13_25-04_00.txt"

## Temporary directory
tempdir: "/fastscratch/barthf/GLASS-WG/tmp"

wgs_scatterdir: "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/b37/scattered_wgs_intervals/scatter-50"

## GnomAD VCF file
gnomad_vcf: "/projects/barthf/GTex-somatic/data/gnomad/af-only-gnomad.raw.sites.b37.vcf.gz"

## Tiny vcf
tiny_vcf: "/projects/barthf/GTex-somatic/data/gnomad/small_exac_common_3_b37.vcf.gz"

vcf2maf: "/projects/barthf/opt/mskcc-vcf2maf-747a1bb/vcf2maf.pl"

veppath: "/projects/barthf/opt/ensembl-vep"

## VEP cache directory
vepdata: "/projects/barthf/opt/.vep"

## Reference genome
reference_fasta: "/projects/barthf/hg19broad/Homo_sapiens_assembly19.fasta"

## HTML dir
html_dir: "/home/barthf/ShinyApps"

## JAVA options
standard_java_opt: "'-Xmx12G'"
samtofastq_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.compression_level=1 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx128m'"
mergebamalignment_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.use_async_io=true -Dsamjdk.compression_level=1 -XX:+UseStringCache -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx5000m'"

#### TEST PARAMETERS
# Uncomment parameters below to activate test mode

## Extra args for revertsam, testing purpose only
revertsam_extra_args : "--MAX_DISCARD_FRACTION=0.05 " 

sample_json: "/projects/barthf/GLASS-WG/data/ref/test_samples_v2.json" 

cluster_json: "/projects/barthf/GLASS-WG/test_cluster.json"

workdir: "/projects/barthf/GLASS-WG"