## Snakemake configuration
## @Author Floris Barthel

## Full path to cluster settings
cluster_json:     "/fastscratch/verhaak-lab/GLASS-WG/conf/cluster.json"

## Working directory
workdir:          "/fastscratch/verhaak-lab/GLASS-WG"

## HTML dir
# @sbamin helix ~/ has 50GB limit. multiqc and fastqc files may grow in size.
html_dir:         "/home/barthf/ShinyApps/"

#### JSON files
cases_json:       "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/cases.json"
samples_json:     "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/samples.json"
aliquots_json:    "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/aliquots.json"
files_json:       "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/files.json"
readgroups_json:  "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/readgroups.json"
pairs_json:       "/fastscratch/verhaak-lab/GLASS-WG/data/manifest/pairs.json"

#### GLOBAL PARAMETERS

## Full path to GDC keyfile
gdc_token:        "/home/barthf/gdc-user-token.2018-05-23T11_13_25-04_00.txt"

## Temporary directory
tempdir:          "/fastscratch/verhaak-lab/GLASS-WG/tmp"

## WGS scatter intervals
wgs_scatterdir:   "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/b37/scattered_wgs_intervals/scatter-50"

## CNV intervals
cnv_intervals:    "/fastscratch/verhaak-lab/GLASS-WG/data/ref/human_g1k_v37_decoy_CNV.interval_list"

## Reference genome
reference_fasta:  "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/b37/human_g1k_v37_decoy.fasta"

## Reference dictionary
reference_dict:   "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/b37/human_g1k_v37_decoy.dict"

## GnomAD VCF file
gnomad_vcf:       "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/Mutect2/af-only-gnomad.raw.sites.b37.vcf.gz"

## Tiny VCF
tiny_vcf:         "/projects/verhaak-lab/verhaak_ref/gatk-legacy-bundles/Mutect2/GetPileupSummaries/small_exac_common_3_b37.vcf.gz"

## Vcf2MAF Perl Script location
vcf2maf:          "/projects/barthf/opt/mskcc-vcf2maf-747a1bb/vcf2maf.pl"

## VEP installation
veppath:          "/projects/barthf/opt/ensembl-vep"

## VEP cache directory
vepdata:          "/projects/barthf/opt/.vep"

## Based on GATK best practices RNAseq 04/05/18
## https://software.broadinstitute.org/gatk/documentation/article.php?id=3891
## Calculate af-of-alleles: 1/(2*123136) = 0.00000406055 (6 sign. digits)
af_of_alleles_not_in_resource: 0.00000406055

seconds_between_progress_updates: 900

## JAVA options
samtofastq_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.compression_level=1 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx128m'"
mergebamalignment_java_opt: "'-Dsamjdk.buffer_size=131072 -Dsamjdk.use_async_io=true -Dsamjdk.compression_level=1 -XX:+UseStringCache -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -Xmx5000m'"

#### ACTUAL RUN
revertsam_extra_args : ""

## END ##